server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/je?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: cloud
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver

je:
  jwt:
    #enabled:
    secret: abcdefg1234567 # 加密密钥
    expire: 3600 # token有效时长
    header: token # header 名称
    ignorepath: /comm,/error,/favicon.ico,swagger,/csrf

logging:
  level:
    com.je: debug

swagger2:
  docket:
    apiInfo:
      title: 测试demo
    basePackage: com.je.cloud



