server:
  port: 80

spring:
  application:
    name: document
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .html
    template-loader-path: classpath:/templates/
  resources:
    static-locations: classpath:/static/

je:
  jwt:
    enabled: false
    secret: abcdefg1234567 # 加密密钥
    expire: 3600 # token有效时长
    header: token # header 名称
    ignore-path: /comm,/error,/favicon.ico,swagger,/csrf,/getfile/
    ignore-ip: 127.0.0.1,172.17.0.2,10.8.10.205



#  文档转换回调地址
#  {
#    "endConvert": true,
#    "fileUrl": "https://documentserver/ResourceService.ashx?filename=output.doc",
#    "percent": 100
#  }
  document:
    filesizeMax: 5242880
    #storage-folder: /app/dapp/document/temp/
    storageFolder: /Users/shengte/git/temp/
    viewedDocs: .pdf|.djvu|.xps
    editedDocs: .docx|.xlsx|.csv|.pptx|.txt
    convertDocs: .docm|.dotx|.dotm|.dot|.doc|.odt|.fodt|.ott|.xlsm|.xltx|.xltm|.xlt|.xls|.ods|.fods|.ots|.pptm|.ppt|.ppsx|.ppsm|.pps|.potx|.potm|.pot|.odp|.fodp|.otp|.rtf|.mht|.html|.htm|.epub
    timeout: 120000
    converterUrl: http://10.8.10.205:8081/ConvertService.ashx
    tempstorageUrl: http://10.8.10.205:8081/ResourceService.ashx
    apiUrl: http://10.8.10.205:8081/web-apps/apps/api/documents/api.js
    preloaderUrl: http://10.8.10.205:8081/web-apps/apps/api/documents/cache-scripts.html
    secret:
  # header: Authorization

logging:
  level:
    com.je: debug

swagger2:
  docket:
    apiInfo:
      title: 测试demo
    basePackage: com.je.cloud



