server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/je?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: cloud
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
redis:
  database: 1
  host: 10.19.2.211
  port: 6379
  password: caih123
  jedis:
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最小空闲连接
      min-idle: 0

je:
  jwt:
    #    enabled:
    secret: abcdefg1234567 # 加密密钥
    expire: 3600 # token有效时长
    header: token # header 名称
    ignorepath: /comm,/error,/favicon.ico,swagger,/csrf

logging:
  level:
    com.je: info

swagger2:
  docket:
    apiInfo:
      title: 测试demo
    basePackage: com.je.cloud



